// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDw-K4CavzFIuGnU3IOi9zrbJ7iRVPsCwY',
    appId: '1:155329048080:web:4503516c1ed5ea9e6ba495',
    messagingSenderId: '155329048080',
    projectId: 'session6-126d6',
    authDomain: 'session6-126d6.firebaseapp.com',
    storageBucket: 'session6-126d6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDLILO15FuLe2A4iFcRTgfr6Bm7OGOVR8',
    appId: '1:155329048080:android:f17390cf3bbeb7006ba495',
    messagingSenderId: '155329048080',
    projectId: 'session6-126d6',
    storageBucket: 'session6-126d6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATTDYMNRSyKfmt5YvwJ1wbnVq9DX3kR9M',
    appId: '1:155329048080:ios:34c0078ffd943ba56ba495',
    messagingSenderId: '155329048080',
    projectId: 'session6-126d6',
    storageBucket: 'session6-126d6.firebasestorage.app',
    iosBundleId: 'com.example.session4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATTDYMNRSyKfmt5YvwJ1wbnVq9DX3kR9M',
    appId: '1:155329048080:ios:34c0078ffd943ba56ba495',
    messagingSenderId: '155329048080',
    projectId: 'session6-126d6',
    storageBucket: 'session6-126d6.firebasestorage.app',
    iosBundleId: 'com.example.session4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDw-K4CavzFIuGnU3IOi9zrbJ7iRVPsCwY',
    appId: '1:155329048080:web:4074e973db6cd0fe6ba495',
    messagingSenderId: '155329048080',
    projectId: 'session6-126d6',
    authDomain: 'session6-126d6.firebaseapp.com',
    storageBucket: 'session6-126d6.firebasestorage.app',
  );
}
